version: "2"

services:
  base:
    stdin_open: true # docker run -i
    tty: true # docker run -t
    build:
      context: .
      dockerfile: ./src/liquidator/Dockerfile
    environment:
      EARNINGS_WALLET: ${EARNINGS_WALLET}
      CHAIN_ID: ${CHAIN_ID}
      REDIS_URL: "redis://:${REDIS_PASSWORD}@redis:6379/0"
      PEER_COUNT: ${PEER_COUNT}
      PEER_INDEX: ${PEER_INDEX}
      SEED_PHRASE: ${SEED_PHRASE}
      ACCOUNTS_PER_BOT: ${ACCOUNTS_PER_BOT}
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "10"
