# sudo docker compose up --build -d
version: "2"

name: d8x

services:
  # Redis for Pub/Sub between blockchain listener (pub) and liquidators (sub)
  redis:
    image: redis
    environment:
      - REDIS_ARGS=--requirepass ${REDIS_PASSWORD}
    ports:
      - "127.0.0.1:6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}

  # Listen to block and events, and stream on redis
  sentinel:
    build:
      context: .
      dockerfile: ./src/sentinel/Dockerfile
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379/0
      - SDK_CONFIG=${SDK_CONFIG}
    restart: on-failure

  # Account manager: fetches and distributes data to liquidators
  commander:
    depends_on:
      - sentinel
    build:
      context: .
      dockerfile: ./src/commander/Dockerfile
    environment:
      - REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379/0
      - SDK_CONFIG=${SDK_CONFIG}
    restart: on-failure

  # liquidator: submits liquidate calls to the blockchain
  executor:
    depends_on:
      - commander
    build:
      context: .
      dockerfile: ./src/executor/Dockerfile
    environment:
      - REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379/0
      - SDK_CONFIG=${SDK_CONFIG}
      - SEED_PHRASE=${SEED_PHRASE}
      - FROM=1
      - TO=2
    restart: on-failure
