version: "2"

services:
  # Redis for Pub/Sub between blockchain listener (pub) and liquidators (sub)
  redis:
    image: redis
    environment:
      - REDIS_ARGS=--requirepass ${REDIS_PASSWORD}
    ports:
      - "127.0.0.1:6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}

  # Listen to block and events, and stream on redis
  blockchain-streamer:
    build:
      context: .
      dockerfile: ./src/listener/Dockerfile
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379/0
      - RPC_HTTP_URL=${RPC_HTTP_URL}
      - RPC_WS_URL=${RPC_WS_URL}
    restart: on-failure

  # Liquidators
  liquidator-1:
    depends_on:
      - blockchain-streamer
    build:
      context: .
    extends:
      file: base.yml
      service: base
    environment:
      - SYMBOL=ETH-USD-MATIC
      - WALLET_INDEX=1

  liquidator-2:
    depends_on:
      - blockchain-streamer
    extends:
      file: base.yml
      service: base
    environment:
      - SYMBOL=BTC-USD-MATIC
      - WALLET_INDEX=2

  liquidator-3:
    depends_on:
      - blockchain-streamer
    extends:
      file: base.yml
      service: base
    environment:
      - SYMBOL=MATIC-USD-MATIC
      - WALLET_INDEX=3

  liquidator-4:
    depends_on:
      - blockchain-streamer
    extends:
      file: base.yml
      service: base
    environment:
      - SYMBOL=ETH-USDC-USDC
      - WALLET_INDEX=4

  liquidator-5:
    depends_on:
      - blockchain-streamer
    extends:
      file: base.yml
      service: base
    environment:
      - SYMBOL=MATIC-USDC-USDC
      - WALLET_INDEX=5

  liquidator-6:
    depends_on:
      - blockchain-streamer
    extends:
      file: base.yml
      service: base
    environment:
      - SYMBOL=BTC-USDC-USDC
      - WALLET_INDEX=6

  liquidator-7:
    depends_on:
      - blockchain-streamer
    extends:
      file: base.yml
      service: base
    environment:
      - SYMBOL=CHF-USDC-USDC
      - WALLET_INDEX=7

  liquidator-8:
    depends_on:
      - blockchain-streamer
    extends:
      file: base.yml
      service: base
    environment:
      - SYMBOL=GBP-USDC-USDC
      - WALLET_INDEX=8
