module.exports = {
  apps: [
    {
      name: "MATIC-USD-MATIC",
      script: "dist/src/liquidator/main.js",
      watch: ["dist/src", "./node_modules/"],
      error_file: "./logs/liquidator-errors.log",
      out_file: "./logs/liquidations.log",
      args: "MATIC-USD-MATIC 0",
      namespace: "liquidator",
    },
    {
      name: "ETH-USD-MATIC",
      script: "dist/src/liquidator/main.js",
      watch: ["dist/src", "./node_modules/"],
      error_file: "./logs/liquidator-errors.log",
      out_file: "./logs/liquidations.log",
      args: "ETH-USD-MATIC 1",
      namespace: "liquidator",
    },
    {
      name: "BTC-USD-MATIC",
      script: "dist/src/liquidator/main.js",
      watch: ["dist/src", "./node_modules/"],
      error_file: "./logs/liquidator-errors.log",
      out_file: "./logs/liquidations.log",
      args: "BTC-USD-MATIC 2",
      namespace: "liquidator",
    },
    {
      name: "MATIC-USDC-USDC",
      script: "dist/src/liquidator/main.js",
      watch: ["dist/src", "./node_modules/"],
      error_file: "./logs/liquidator-errors.log",
      out_file: "./logs/liquidations.log",
      args: "MATIC-USDC-USDC 3",
      namespace: "liquidator",
    },
    {
      name: "ETH-USDC-USDC",
      script: "dist/src/liquidator/main.js",
      watch: ["dist/src", "./node_modules/"],
      error_file: "./logs/liquidator-errors.log",
      out_file: "./logs/liquidations.log",
      args: "ETH-USDC-USDC 4",
      namespace: "liquidator",
    },
    {
      name: "BTC-USDC-USDC",
      script: "dist/src/liquidator/main.js",
      watch: ["dist/src", "./node_modules/"],
      error_file: "./logs/liquidator-errors.log",
      out_file: "./logs/liquidations.log",
      args: "BTC-USDC-USDC 5",
      namespace: "liquidator",
    },
    {
      name: "CHF-USDC-USDC",
      script: "dist/src/liquidator/main.js",
      watch: ["dist/src", "./node_modules/"],
      error_file: "./logs/liquidator-errors.log",
      out_file: "./logs/liquidations.log",
      args: "CHF-USDC-USDC 6",
      namespace: "liquidator",
    },
    {
      name: "GBP-USDC-USDC",
      script: "dist/src/liquidator/main.js",
      watch: ["dist/src", "./node_modules/"],
      error_file: "./logs/liquidator-errors.log",
      out_file: "./logs/liquidations.log",
      args: "GBP-USDC-USDC 7",
      namespace: "liquidator",
    },
    // {
    //   name: "XAU-USDC-USDC",
    //   script: "dist/src/liquidator/main.js",
    //   watch: ["./src", "./node_modules/"],
    //   error_file: "./logs/liquidator-errors.log",
    //   out_file: "./logs/liquidations.log",
    //   args: "XAU-USDC-USDC 8",
    //   namespace: "liquidator"
    // },
    {
      name: "Watchdog",
      script:
        "node dist/src/runWatchDog.js MATIC-USD-MATIC ETH-USD-MATIC BTC-USD-MATIC MATIC-USDC-USDC ETH-USDC-USDC BTC-USDC-USDC CHF-USDC-USDC GBP-USDC-USDC",
      watch: ["dist/src"],
      error_file: "./logs/watchdog-errors.log",
      out_file: "./logs/watchdog.log",
      namespace: "liquidator",
    },
  ],
};
