# sudo docker compose -f perpetuals-testnet.yml up --build -d
version: "2"

name: d8x

services:
  # Redis for Pub/Sub between blockchain listener (pub) and liquidators (sub)
  redis:
    image: redis
    environment:
      - REDIS_ARGS=--requirepass ${REDIS_PASSWORD}
    ports:
      - "127.0.0.1:6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}

  # Listen to block and events, and stream on redis
  listener:
    build:
      context: .
      dockerfile: ./src/listener/Dockerfile
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379/0
      - SDK_CONFIG=${SDK_CONFIG}
    restart: on-failure

  # Account manager: fetches and distributes data to liquidators
  distributor:
    depends_on:
      - listener
    build:
      context: .
      dockerfile: ./src/distributor/Dockerfile
    environment:
      - REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379/0
      - SDK_CONFIG=${SDK_CONFIG}
    restart: on-failure

  # liquidator: submits liquidate calls to the blockchain
  liquidator-1:
    depends_on:
      - distributor
    build:
      context: .
      dockerfile: ./src/liquidator/Dockerfile
    environment:
      - REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379/0
      - SDK_CONFIG=${SDK_CONFIG}
      - SEED_PHRASE=${SEED_PHRASE}
      - FROM=1
      - TO=2
    restart: on-failure
