# Run: sudo docker compose -f perpetuals.yml up --build -d

version: "2"

services:
  # Redis
  ## For Pub/Sub between blockchain listener (pub) and executors (sub)
  redis:
    image: redis
    environment:
      - REDIS_ARGS=--requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    restart: on-failure

  # Blockain Streamer
  ## Listen to block and events, and stream on redis
  blockchain-streamer:
    build:
      context: .
      dockerfile: ./src/listener/Dockerfile
    depends_on:
      - redis
    environment:
      - CHAIN_ID=${CHAIN_ID}
      - REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379/0
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"

  # Liquidators
  ## One service per bot/perpetual. Example:

  eth-usd-matic:
    depends_on:
      - blockchain-streamer
    build:
      context: .
    extends:
      file: liquidator.yml
      service: base
    environment:
      - SYMBOL=ETH-USDC-USDC
      - WALLET_INDEX=1
