name: cleanup merged branches

on:
  pull_request:
    types: [closed]
  schedule:
    - cron: "0 3,15 * * *"
  workflow_dispatch:

jobs:
  cleanup:
    uses: D8-X/reusable-gh-workflows/.github/workflows/delete-merged-branch.yml@main
    permissions:
      contents: write
      pull-requests: read
